import z3
from asm_analyzer.engine.tracker import Tracker, TraceRecord, Descendant
from asm_analyzer.engine.translator import Z3Translator

def main():
    tracker = Tracker()
    
    # Fake Trace Log reflecting the AI Warning Scenario
    # 1. ADD modifies all flags
    t1 = TraceRecord(tick=1, address=0x1000, mnemonic="add", op_str="eax, ebx")
    t1.regs_read = ["eax", "ebx"]
    t1.regs_write = ["eax", "eflags"]
    tracker.add_trace(t1)
    
    # 2. INC modifies all flags EXCEPT CF (The Bug Trap!)
    t2 = TraceRecord(tick=2, address=0x1002, mnemonic="inc", op_str="eax")
    t2.regs_read = ["eax"]
    t2.regs_write = ["eax", "eflags"]
    tracker.add_trace(t2)
    
    # 3. JB checks CF
    t3 = TraceRecord(tick=3, address=0x1004, mnemonic="jb", op_str="0x1020")
    t3.regs_read = ["eflags"]
    t3.regs_write = []
    tracker.add_trace(t3)
    
    print("\n[+] Starting Path Extraction for 'jb' (depends on CF)")
    descendant = Descendant(target="jmp_condition", at_tick=3)
    
    # Hack the tracker to start searching for control flow immediately from the JB instruction
    # Normally this happens when a taint breaker is hit, but we simulate starting from the branch itself
    tracker_dummy = Tracker()
    tracker_dummy.trace_history = tracker.trace_history
    
    # Build slice explicitly requesting CF by spoofing the jump
    slice_instructions = []
    targets_to_track = set(["flag_cf"])
    print(f"[*] Starting Backward Slicing for CF from Tick 3")
    
    for tick in range(3, 0, -1):
        record = tracker_dummy.get_trace_at_tick(tick)
        if not record: continue
        
        writes_to_tracked_flag = False
        flags_to_kill = []
        
        tracked_flags = [t for t in targets_to_track if isinstance(t, str) and t.startswith("flag_")]
        if tracked_flags and "eflags" in record.regs_write:
            if record.mnemonic in tracker_dummy.MODIFIES_ALL_FLAGS:
                writes_to_tracked_flag = True
                flags_to_kill.extend(tracked_flags)
                record.requested_flags.extend(tracked_flags)
                print(f"  -> [Flag Gen] Hit {record.mnemonic} at Tick {record.tick}, which satisfies {tracked_flags}")
            elif record.mnemonic in tracker_dummy.MODIFIES_ZSO_ONLY:
                affected_flags = [f for f in tracked_flags if f != "flag_cf"]
                if affected_flags:
                    writes_to_tracked_flag = True
                    flags_to_kill.extend(affected_flags)
                    record.requested_flags.extend(affected_flags)
                    print(f"  -> [Flag Gen] Hit {record.mnemonic} at Tick {record.tick}, which satisfies {affected_flags}")
                elif "flag_cf" in tracked_flags:
                    print(f"  -> [Flag Ignore] Hit {record.mnemonic} at Tick {record.tick}, but it DOES NOT modify CF. Skipping!")
        
        if writes_to_tracked_flag:
            slice_instructions.append(record)
            for f in flags_to_kill:
                targets_to_track.remove(f)
            # Add sources of the flag setter
            for r in record.regs_read:
                targets_to_track.add(r)
    
    # Complete slice extraction for the rest of targets
    print("\n[+] Extracted Slice Instructions:")
    for instr in slice_instructions:
        print(f"    {instr} (Requested Flags: {instr.requested_flags})")
        
    print("\n[+] Testing Lazy Z3 Translation")
    translator = Z3Translator()
    
    # Initialize physical registers
    eax = translator._get_phys_reg("eax")
    ebx = translator._get_phys_reg("ebx")
    
    # We want JB to be True (CF == True)
    # EAX + EBX must overflow 32-bit bound
    translator.solver.add(eax == 0xFFFFFFFF)
    translator.solver.add(ebx == 0x2)
    
    translator.translate_slice(slice_instructions)
    
    # Manually extract the CF flag generated (since Z3Translator stores it in flag_state)
    cf_flag = translator.flag_state.get("flag_cf")
    if cf_flag is not None:
        print(f"\n[+] CF Flag Formula Generated: {cf_flag}")
        translator.solver.add(cf_flag == True)
        
        if translator.solver.check() == z3.sat:
            print("[SUCCESS] Z3 Satisfied the CF condition!")
            m = translator.solver.model()
            print(f"    EAX = {m[eax]}")
            print(f"    EBX = {m[ebx]}")
        else:
            print("[X] FAILURE: Z3 could not satisfy the condition.")
    else:
        print("[X] FAILURE: CF Flag was not generated by translator!")

if __name__ == "__main__":
    main()
